// @flow

export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const UPDATE_DOWNLOAD_PROGRESS = "UPDATE_DOWNLOAD_PROGRESS";
export const REGISTER_ASSET = "REGISTER_ASSET";
export const DELETE_ALL_MEDIA = "DELETE_ALL_MEDIA";
